services:
  attribute-authority:
    container_name: ade-aa-ms
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - NODE_TLS_REJECT_UNAUTHORIZED=0
    env_file:
      - .env
    expose:
      - "3000"
    ports:
      - "3000:3000"
      - "5859:5859"
    image: node:20.11.1-alpine
    command: ["yarn", "start"]
    volumes:
      - ".:/usr/src/app:cached"
    networks:
      - attribute-authority

networks:
  attribute-authority:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1450
