name: Deploy App Service (onboarding-portal-backend-ms)

on:
  workflow_dispatch: {}
  push:
    branches:
      - master
    paths:
      - ".github/workflows/deploy-onboarding-portal-backend-ms.yaml"

jobs:

  deploy_uat:
    name: Deploy Onboarding Portal Backend UAT
    uses: ./.github/workflows/java_web_app_deploy.yaml
    secrets: inherit
    with:
      app_folder: cgn-onboarding-portal-backend
      environment: pe-app-uat
      resource_group_name: io-u-itn-cgn-pe-rg-01
      web_app_name: io-u-itn-cgn-pe-backend-app-01
      use_staging_slot: true
      use_private_agent: true
      use_labels: true

  deploy_prod:
    needs: deploy_uat
    name: Deploy Onboarding Portal Backend PROD
    uses: ./.github/workflows/java_web_app_deploy.yaml
    secrets: inherit
    with:
      app_folder: cgn-onboarding-portal-backend
      environment: pe-app-prod
      resource_group_name: io-p-itn-cgn-pe-rg-01
      web_app_name: io-p-itn-cgn-pe-backend-app-01
      use_staging_slot: true
      use_private_agent: true
      use_labels: true