name: Deploy App Service (onboarding-portal-backend-ms)

on:
  workflow_dispatch: 
    inputs:
      revision:
        description: You can specify a revision to deploy as any commit hash or branch name
        type: string
        required: false
        default: "master"
  push:
    branches:
      - master
    paths:
      - ".github/workflows/deploy-onboarding-portal-backend-ms.yaml"

jobs:

  deploy_uat:
    name: Deploy Onboarding Portal Backend UAT
    uses: ./.github/workflows/java_web_app_deploy.yaml
    secrets: inherit
    with:
      app_folder: cgn-onboarding-portal-backend
      environment: uat
      resource_group_name: io-u-itn-cgn-pe-rg-01
      web_app_name: io-u-itn-cgn-pe-backend-app-01
      use_staging_slot: true
      use_private_agent: true
      use_labels: true
      revision: ${{inputs.revision}}

  deploy_prod:
    needs: deploy_uat
    name: Deploy Onboarding Portal Backend PROD
    uses: ./.github/workflows/java_web_app_deploy.yaml
    secrets: inherit
    with:
      app_folder: cgn-onboarding-portal-backend
      environment: prod
      resource_group_name: io-p-itn-cgn-pe-rg-01
      web_app_name: io-p-itn-cgn-pe-backend-app-01
      use_staging_slot: true
      use_private_agent: true
      use_labels: true
