name: Deploy Function App (search-func)

on:
  workflow_dispatch: {}
  push:
    branches:
      - master
    paths:
      - "apps/search-func/CHANGELOG.md"
      - ".github/workflows/deploy-search-func.yaml"

jobs:

  deploy:
    name: Deploy Search Func
    uses: pagopa/dx/.github/workflows/function_app_deploy.yaml@main
    secrets: inherit
    with:
      workspace_name: search-func
      environment: io-app-prod
      resource_group_name: io-p-itn-cgn-rg-01
      function_app_name: io-p-itn-cgn-search-func-01
      health_check_path: "/api/v1/cgn/operator-search/info"
      use_staging_slot: true