name: PR Infrastructure Plan IO

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
    paths:
      - ".github/workflows/infra-**-io.yaml"
      - "infra-io/resources/**"

jobs:
  infra_review:
    uses: pagopa/dx/.github/workflows/infra_plan.yaml@97bbfc7461fc312123f78158fe2c47563d8c7571
    name: Infra review IO PROD
    secrets: inherit
    with:
      environment: prod
      base_path: infra-io/resources
      override_github_environment: io-prod
      use_private_agent: true
      use_labels: true
      override_labels: io-prod