name: Release Infrastructure Portale Esercenti

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "infra-pe/resources/**"

jobs:
  infra_release_uat:
    uses: pagopa/dx/.github/workflows/infra_apply.yaml@main
    name: Release Infrastructure PE UAT
    secrets: inherit
    with:
      environment: uat
      base_path: infra-pe/resources
      use_private_agent: true

  infra_release_prod:
    uses: pagopa/dx/.github/workflows/infra_apply.yaml@main
    name: Release Infrastructure PE PROD
    secrets: inherit
    with:
      environment: prod
      base_path: infra-pe/resources
      use_private_agent: true
