name: Release Infrastructure IO

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "infra-io/resources/**"

jobs:
  infra_release:
    uses: pagopa/dx/.github/workflows/infra_apply.yaml@main
    name: Release Infrastructure IO PROD
    secrets: inherit
    with:
      environment: prod
      base_path: infra-io/resources
      use_private_agent: true
