name: Release crossrepo test

on:
  workflow_dispatch: 
    inputs:
      revision:
        description: You can specify a revision to deploy as any commit hash or branch name
        type: string
        required: false
        default: "master"
      release_type:
        type: choice
        description: The type of release to build
        options: 
          - patch
          - minor
          - major
  push:
    branches:
      - master

jobs:
  release_prod:
    name: RELEASE Onboarding Portal Backend PROD
    uses: ./.github/workflows/release_test.yaml
    secrets: inherit
    with:
      app_folder: cgn-onboarding-portal-backend
      environment: prod
      resource_group_name: io-p-itn-cgn-pe-rg-01
      web_app_name: io-p-itn-cgn-pe-backend-app-01
      use_staging_slot: true
      use_private_agent: true
      use_labels: true
      revision: ${{inputs.revision}}
      release_type: ${{inputs.release_type}}
