name: Renew AGW Certs Portale Esercenti

on:
  workflow_dispatch: {}
  schedule:
    - cron: '0 2 1 * *'  # At 02:00 on day-of-month 1

jobs:
  renew_uat:
    uses: pagopa/io-infra/.github/workflows/ssl_certificate_renewal.yaml@b04e50d300f48d840b77d5e913ede0d8a605aa4f
    name: Renew PE UAT certificate
    secrets: inherit
    with:
        csr_common_name: api.cgnonboardingportal-uat.pagopa.it
        azure_dns_zone_resource_group: cgnonboardingportal-u-public-rg
        azure_dns_zone: cgnonboardingportal-uat.pagopa.it
        key_vault_name: io-u-itn-cgn-pe-kv-01
        force_renew_cert: true
        environment: pe-uat
        use_selfhosted_agent: true

  renew_prod:
    uses: pagopa/io-infra/.github/workflows/ssl_certificate_renewal.yaml@b04e50d300f48d840b77d5e913ede0d8a605aa4f
    name: Renew PE PROD certificate
    secrets: inherit
    needs: [renew_uat]
    with:
        csr_common_name: api.cgnonboardingportal.pagopa.it
        azure_dns_zone_resource_group: cgnonboardingportal-p-public-rg
        azure_dns_zone: cgnonboardingportal.pagopa.it
        key_vault_name: io-p-itn-cgn-pe-kv-01
        force_renew_cert: true
        environment: pe-prod
        use_selfhosted_agent: true
      