name: (Release) GitHub Runner WestEurope

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "infra/github-runner/**"

jobs:
  runner_release:
    uses: pagopa/dx/.github/workflows/infra_apply.yaml@723b8233cd9c48bac7cc9e796471d4e12d4f8e5c # main
    name: Release Prod WestEurope
    secrets: inherit
    with:
      environment: "prod"
      base_path: "infra/github-runner"
