name: (Release) GitHub Runner WestEurope

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "infra/github-runner/**"

jobs:
  runner_release:
    uses: pagopa/dx/.github/workflows/infra_apply.yaml@a18d71062ddaaa09f8e145835a05aefd7701935e # main
    name: Release Prod WestEurope
    secrets: inherit
    with:
      environment: "prod"
      base_path: "infra/github-runner"
