name: (Release) GitHub Runner WestEurope

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "infra/github-runner/**"

jobs:
  runner_release:
    uses: pagopa/dx/.github/workflows/infra_apply.yaml@625f02f382c33eb449cd94facb8e426bf7ae37ea # main
    name: Release Prod WestEurope
    secrets: inherit
    with:
      environment: "prod"
      base_path: "infra/github-runner"
